### PR TITLE
Fix y-axis format issues in charts such as the UK NI LEL parameter chart

### LINKED ISSUE #854: UK NI LEL parameter chart y axis broken
image

https://policyengine.org/uk/policy?focus=gov.hmrc.national_insurance.class_1.thresholds.lower_earnings_limit

### PR DESCRIPTION
**Pull request by abhcs**
## Description

Fixed #854 by changing the calculation of the axis format in `getPlotlyAxisFormat`. This pull request also has implications for #425 and #66: the format issues for MTR should go away and the range of the y-axis should rarely exceed 100%.

## Method for fix

* Change `getPlotlyAxisFormat`
  * Remove unnecessary arguments.
  * Calculate the number of fractional digits to be displayed in a more sophisticated manner.
* Display the variable label in `EarningsVariation` chart's title and description.
* Fix the `MarginalTaxRates` description.
* In `EarningsVariation` and `MarginalTaxRates` charts,
  * Do not forcibly set precision using `tickformat`.
  * Instead depend on passing all `x` and `y` values to `getPlotlyAxisFormat`.

## Tests

I have checked that the axes in `EarningsVariation`, `MarginalTaxRates`, and `ParameterOverTime` charts are displayed properly.

Screenshot 2023-12-07 at 9 09 18 PM

Screenshot 2023-12-07 at 9 11 34 PM

Screenshot 2023-12-07 at 9 16 47 PM

### Summary
📊💰🧹

This pull request improves the data formatting and presentation of various plotly charts in the app. It refactors the code to use a common function `getPlotlyAxisFormat` for determining the best axis format for different types of variables. It also makes some minor style and naming changes, and makes the `ResultsPanel` component more flexible for different variables.

> _The `ResultsPanel` got a makeover_
> _With dynamic titles and axes to show for_
> _The data was refactored_
> _The style was adapted_
> _And the code became cleaner and lower_

### Walkthrough
*  Refactor `getPlotlyAxisFormat` function to handle different currency units, precision, and range based on the values passed as an argument, and to handle boolean or binary variables ([link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b5951a72ed1475216756f45c9a54ea34fb15cce384284eb48b32a30c5c0bf58bL220-R257), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b5951a72ed1475216756f45c9a54ea34fb15cce384284eb48b32a30c5c0bf58bL295-R282))
* Replace hardcoded or fixed values with dynamic values based on the `variableLabel` prop, the `xaxisValues` and `yaxisValues` arrays, and the `getPlotlyAxisFormat` function calls in the `ResultsPanel` and chart components for earnings variation, marginal tax rates, and parameter over time ([link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-31d25016a1cb4e96f8c2752f8f09fff24d1917b85c379be5008c6dd494596efaL180-R181), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL151-R176), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL179-R196), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL199-R216), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL220-R237), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL251-R268), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL259-R276), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL362-R385), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL384-R405), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL417-R438), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-2d2999e2b861d5ecd207303d30de01038af3b1635fca08bdd0d821159476f39bL426-R446), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98R62-R74), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L69-R85), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L99-R105), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L125-R131), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L135-R141), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9R131-R136), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L143-R150), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L158-R165), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L178-R185), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L188-R195), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L258-R277), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L279-R292), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L295-R318), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L312-R333), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L327-R348), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L342-R363), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L396-R416), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L404-R423), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L440-R457), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b668174e6bcd7b963e980d1a5951bb5209b5fc87dfa52c8dfe35588442c77691L26-R35), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b668174e6bcd7b963e980d1a5951bb5209b5fc87dfa52c8dfe35588442c77691L42-R53), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b668174e6bcd7b963e980d1a5951bb5209b5fc87dfa52c8dfe35588442c77691L94-R89))
* Rename variables to reflect the actual data they contain and to be consistent with the other components in the `BaselineOnlyChart`, `MarginalTaxRates`, and `ParameterOverTime` components ([link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L35-R35), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-7b9bb2a68257e29011e5df68ce37c70dd3747090a38aeef8e27570c7eccdfc98L50-R50), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-43f598ac8f8928c8be5adb376f0f5e8d25a5f61fb6dea523f1157c84d2517ed9L369), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-b668174e6bcd7b963e980d1a5951bb5209b5fc87dfa52c8dfe35588442c77691L42-R53))
* Add trailing commas to the style objects for the `FormHelperText` and `Typography` components, to follow the code style convention and improve readability ([link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-0b81874428a27ccaf5252b5162021f2e5cb92ef0dd9b47834bbcfab1eac56ed6L116-R116), [link](https://github.com/PolicyEngine/policyengine-app/pull/939/files?diff=unified&w=0#diff-0b81874428a27ccaf5252b5162021f2e5cb92ef0dd9b47834bbcfab1eac56ed6L127-R127))

### CODE REVIEW

File: src/api/variables.js [hunk 1]
```diff
@@ -217,62 +217,44 @@ export function formatVariableValue(variable, value, precision = 2) {
...
+
+  const range = () => {
+    return values ? [Math.min(0, ...values), Math.max(0, ...values)] : [0, 0];
+  };
+
+  const paddedRange = () => {
+    const r = range();
+    const d = r[1] - r[0];
+    const p = d * 0.1;
+    return [r[0] - p, r[1] + p];
```
Comment (nikhilwoodruff) [inline src/api/variables.js:232]: Seems reasonable to me

**Review by nikhilwoodruff — APPROVED** [review]
Thanks @abhcs - these axis choices seem good to me.
