### PR TITLE
fix(login-button): adjust sizes to match COMPUTE POLICY IMPACT button

### LINKED ISSUE #1811: Increase the height of the user profile picture on the navbar to match the COMPUTE POLICY IMPACT button
In a recent reskin, the COMPUTE POLICY IMPACT button gained a slight bit of padding, making it just slightly larger than the user profile picture. As such, the profile image should be increased (height and width) to match it.

### PR DESCRIPTION
**Pull request by CallMeMaverick**
## Description

Fixes #1811. Ensure the login button, profile picture, and hamburger menu are the same size as the COMPUTE POLICY IMPACT button.

## Changes

- Increased height and width by 4px for the login button and profile picture.
- Adjusted the hamburger menu size to match.
- Added responsive design adjustments for mobile view.
- Used state to track screen size and apply conditional styling.

## Screenshots

Screenshot 2024-05-24 at 22 21 26
Screenshot 2024-05-24 at 22 21 52

Closes #1811

### CODE REVIEW

**Comment by anth-volk** [comment]
Would you mind running `make format` and pushing the changes? We require linting of our repositories before merge.

**Comment by CallMeMaverick** [comment]
@anth-volk I am done with formatting

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for your work on this, @CallMeMaverick. While your idea here makes a lot of sense, we actually already have a custom hook that does what you're looking to do, called "useDisplayCategory", in `src/hooks`. When implemented, this returns one of the following strings, corresponding to the current breakpoint: "mobile", "tablet", or "desktop". Could you reimplement this with that instead? This just keeps our code cleaner. Thank you very much for your involvement.

**Comment by anth-volk** [comment]
Thanks, will review later today!

**Comment by CallMeMaverick** [comment]
@anth-volk , hello! Thank you for pointing out. I have already incorporated useDisplayCategory and pushed the changes respectively. Waiting for you review👌🏻

File: src/layout/Header.jsx [hunk 1]
```diff
@@ -209,8 +209,12 @@ function MobileCalculatorButton() {
 function LoginButton() {
   const countryId = useCountryId();
   const { loginWithRedirect, isAuthenticated, user, isLoading } = useAuth0();
+  const displayCategory = useDisplayCategory();
+
   const desiredHeight =
-    style.spacing.HEADER_HEIGHT - BAR_TOP_PADDING - BAR_BOTTOM_PADDING;
+    displayCategory === "mobile"
+      ? 44
+      : style.spacing.HEADER_HEIGHT - BAR_TOP_PADDING - BAR_BOTTOM_PADDING + 4;
```
Comment (anth-volk) [inline src/layout/Header.jsx:217]: One thing we try to avoid as much as possible is avoiding "magic numbers," numbers where we don't really know what they mean, and that's the case with both the 44 and the 4 here. Instead of this, from a code quality perspective, could you change BAR_TOP_PADDING and BAR_BOTTOM_PADDING (defined around line 25) to be 10 when on mobile and 8 on tablet and desktop, then keep this line like it was before? This applies to the change below around line 329, as well.

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for this, @CallMeMaverick. While this does do what we're looking for, I just have a code quality change to request, but after that, this should be good to go. Thanks for your efforts!

**Comment by anth-volk** [comment]
If you could lint this again, you're missing a ";"

**Comment by CallMeMaverick** [comment]
My bad, sorry, now it should be just fine

**Review by anth-volk — CHANGES_REQUESTED** [review]
Just a couple minor naming things so other contributors know why we're instantiating these

**Comment by CallMeMaverick** [comment]
@anth-volk hello, I  am writing to inquire about the current status of the review for the pull request

**Comment by anth-volk** [comment]
@CallMeMaverick Thanks for checking in. Due to some other pressing issues, I wasn't able to review this, but this all looks good to go now! I took the liberty of running the linter again. Please add "Fixes #1811" to your description, other wise the issue won't close. Once that's done, we can merge.

**Review by anth-volk — APPROVED** [review]
Thanks for this, @CallMeMaverick! Will merge after the update to the PR comment, we try to enforce this pretty heavily, as it makes it easier to track issues properly.

**Comment by anth-volk** [comment]
Actually, no problem, forgot I could do it myself!

**Comment by CallMeMaverick** [comment]
@anth-volk thanks a lot! That was my first contribution and I am grateful for continuous guidance and support!

**Comment by anth-volk** [comment]
@CallMeMaverick Not a problem at all!
