### PR TITLE
fix: document title now updating properly

### LINKED ISSUE #1119: Tab title is `Current law (compared against current law)` for no-reform household simulations
e.g. https://policyengine.org/us/household?focus=householdOutput.earnings&household=39237

### PR DESCRIPTION
**Pull request by dotslashbit**
## Description

closes #1119 

## Changes
Used useEffect to update document title

## Screenshots
Screenshot 2024-01-08 at 2 10 43 PM

### CODE REVIEW

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for this, @dotslashbit. That said, I don't believe this solves the issue. What I think Max is looking for here is for, in situations where we're looking only at current law, the `policyLabel` should just be "Current law". There's an issue in the underlying logic where the app seems to think there is a reform, and "Current law" is set as both the reform and the baseline. Could you look into this a bit more and refactor?

**Comment by dotslashbit** [comment]
ok, will update on this PR after refactoring

**Comment by dotslashbit** [comment]
Screenshot 2024-01-11 at 11 45 19 AM

@anth-volk Let me know if there's any correction needed

**Comment by anth-volk** [comment]
This appears to be getting the same README linting message that the other PR is getting. Once you paste your terminal output into that one, I'll try to figure out what's going on.

**Comment by anth-volk** [comment]
@dotslashbit Thanks again for this. I'm actually going to hold off on this until I see the verdict on #1169 because I think the package that that adds (`react-helmet`) would allow far easier updating of the page titles. If #1169 is merged, I hate to do this, I'm hoping to ask you to rewrite the logic in this to instead use the `Helmet` component at the top of the relevant components and just declare a `<title>` tag to fill in the title, as that's far cleaner than what we've been doing so far.

**Comment by dotslashbit** [comment]
ok, no issue

**Comment by dotslashbit** [comment]
@anth-volk As #1169 has been merged, please inform what changes you want me to do, I'll do that

**Comment by anth-volk** [comment]
@dotslashbit If you could keep the logic you wrote to determine the `policyLabel` variable, but where the old code manually set `document.title` in each component, if you could instead use the `react-helmet` package above the output JSX, like this:

```
<Helmet>
  <title>{title}</title>
</Helmet>
{the rest of the code}
```

I'll be honest, I'm new to the package myself, so if you run into any issues, please feel free to check into their docs [here](https://www.npmjs.com/package/react-helmet) or to write again in this thread.

**Comment by dotslashbit** [comment]
Screenshot 2024-01-13 at 2 44 32 AM

**Comment by dotslashbit** [comment]
@anth-volk I have updated the code and its working as expected, please take a look and let me know if there's anything more to be done, thanks

File: src/pages/household/output/HouseholdOutput.jsx [hunk 1]
```diff
@@ -37,12 +38,26 @@ export default function HouseholdOutput(props) {
...
+    policyLabel = "Current law";
+  } else if (reformLabel !== "Current law" && baselineLabel === "Current law") {
     policyLabel = reformLabel;
   } else {
     policyLabel = `${reformLabel} (compared against ${baselineLabel})`;
   }
   let pane;
+  let title;
+  if (policyLabel) {
+    if (focus === "householdOutput.netIncome") {
```
Comment (anth-volk) [inline src/pages/household/output/HouseholdOutput.jsx:51]: Previously, each sub-component within the code managed its own title. Now that we've enabled helmet, can you return that logic so that each component can be more self-contained and we avoid this nested if?

**Review by anth-volk — CHANGES_REQUESTED** [review]

**Review by anth-volk — APPROVED** [review]
This looks great! Thanks so much @dotslashbit.
