### PR TITLE
Reinstate Breadcrumbs

### LINKED ISSUE #2022: Breadcrumbs do not work for navigation on mobile
This PR disabled ability to click breadcrumbs since none of them had pages associated with them. https://github.com/PolicyEngine/policyengine-app/pull/1947

The breadcrumbs should be reinstated with a solution to the missing pages so that they can serve as navigation in mobile.

### PR DESCRIPTION
**Pull request by rachel-lawrie**
Reinstates logic for clicking breadcrumbs in mobile to serve as navigation. 

Note that clicking breadcrumbs were disabled as part of #1947.

## Description

Fixes #2022 
1. Adds back in onClick logic
2. Adds logic to check if the focus has a page associated with it, or if it has children in the tree. If it has children in the tree, the folderpage with the children is returned. If it has a page, then the PolicyOutput page is returned. 

## Screenshots
https://www.loom.com/share/79ab325e6fa0402eb70b7bef0cff72f8?sid=cff59996-d6e2-40ad-a00e-a5e8b0c36868

## Tests

Tested locally (created new policy, clicked through each policy, compared to tree to ensure no pages are missing). 

Also ran  test suite. 8 are failing but not due to any of these changes. I compared to the master branch and all 8 were failing there too.

### CODE REVIEW

**Comment by anth-volk** [comment]
@rachel-lawrie I suspect the test failure was a fluke, as other PRs failed similarly around the same time as yours, except these were incredibly minor. They've also all been re-run and passed.

File: src/pages/PolicyPage.jsx [hunk 1]
```diff
@@ -155,17 +156,88 @@ export default function PolicyPage(props) {
       </FolderPage>
     );
   } else if (isOutput) {
-    middle = (
-      <>
+    // eslint-disable-next-line no-console
+    console.log("focus:" + focus);
```
Comment (anth-volk) [inline src/pages/PolicyPage.jsx:160]: Could you remove this and the below console statements?

File: src/pages/PolicyPage.jsx [hunk 2]
```diff
@@ -155,17 +156,88 @@ export default function PolicyPage(props) {
...
+        );
+      } else {
+        // eslint-disable-next-line no-console
+        console.log("no node");
+        middle = <div>No matching node found.</div>;
+      }
+    }
   }
 
+  // This code works
```
Comment (anth-volk) [inline src/pages/PolicyPage.jsx:216]: I'm a bit unclear as to what this commented code block is for

File: src/pages/PolicyPage.jsx [hunk 3]
```diff
@@ -155,17 +156,88 @@ export default function PolicyPage(props) {
...
+      // Render FolderPage with its children if the node is found
+      if (node) {
+        middle = (
+          <FolderPage label={node.label} metadata={metadata}>
+            {node.children}
+          </FolderPage>
+        );
+      } else {
+        // eslint-disable-next-line no-console
+        console.log("no node");
```
Comment (anth-volk) [inline src/pages/PolicyPage.jsx:210]: Could you remove this console log, as well?

**Review by anth-volk — CHANGES_REQUESTED** [review]
Thanks for this, @rachel-lawrie. Just had a couple code quality requests, then this should be good to merge!

**Review by anth-volk — APPROVED** [review]
Thank you very much @rachel-lawrie!
